steps:
# Step 1: Build the container image AND push it to Artifact Registry
# This single step does the job of the previous two.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/daily-quote-app/quote-image:$COMMIT_SHA'
  - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/daily-quote-app/quote-image:latest' # Also tag as 'latest'
  - '.'
  - '--push=us-central1-docker.pkg.dev/$PROJECT_ID/daily-quote-app/'

# Step 2: Deploy the new image to Cloud Run using the LATEST tag
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'daily-quote-service'
  - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/daily-quote-app/quote-image:latest' # We will use the 'latest' tag for simplicity
  - '--region=us-central1'
  - '--platform=managed'
  - '--allow-unauthenticated'

# This section is no longer strictly needed but is good practice
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/daily-quote-app/quote-image'
options:
  logging: CLOUD_LOGGING_ONLY
